export const enum ConfigParams {
  APP_PORT = 'APP_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES = 'JWT_EXPIRES',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_HOST = 'REDIS_HOST'
}
